### ISSUE TITLE
Error sending empty messages

### ISSUE THREAD

**Issue by andy-trimble** [Archarithms/bigio#23]
The following message throws an exception and is not sent.

```java
@Message
public class EmptyMessage {

}
```

The exception thrown is:

```java
javassist.CannotCompileException: [source error] empty try block
	at javassist.CtNewMethod.make(CtNewMethod.java:79) ~[javassist-3.18.2-GA.jar:na]
	at javassist.CtNewMethod.make(CtNewMethod.java:45) ~[javassist-3.18.2-GA.jar:na]
	at javassist.CtMethod.make(CtMethod.java:130) ~[javassist-3.18.2-GA.jar:na]
	at io.bigio.agent.JATransformer.transform(JATransformer.java:327) ~[bigio-agent-1.1.2-SNAPSHOT.jar:na]
	at io.bigio.agent.MessageTransformer.transform(MessageTransformer.java:82) [bigio-agent-1.1.2-SNAPSHOT.jar:na]
	at sun.instrument.TransformerManager.transform(TransformerManager.java:188) [na:1.8.0_25]
	at sun.instrument.InstrumentationImpl.transform(InstrumentationImpl.java:428) [na:1.8.0_25]
	at java.lang.ClassLoader.defineClass1(Native Method) [na:1.8.0_25]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760) [na:1.8.0_25]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142) [na:1.8.0_25]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:455) [na:1.8.0_25]
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73) [na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:367) [na:1.8.0_25]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361) [na:1.8.0_25]
	at java.security.AccessController.doPrivileged(Native Method) [na:1.8.0_25]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:360) [na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424) [na:1.8.0_25]
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308) [na:1.8.0_25]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357) [na:1.8.0_25]
	at io.bigio.EmptyMessageTest.testMessage(EmptyMessageTest.java:57) [test-classes/:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_25]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_25]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_25]
	at java.lang.reflect.Method.invoke(Method.java:483) ~[na:1.8.0_25]
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:47) [junit-4.11.jar:na]
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12) [junit-4.11.jar:na]
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:44) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:271) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:70) [junit-4.11.jar:na]
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:50) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:238) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:63) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:236) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:53) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:229) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26) [junit-4.11.jar:na]
	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:27) [junit-4.11.jar:na]
	at org.junit.runners.ParentRunner.run(ParentRunner.java:309) [junit-4.11.jar:na]
	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:264) [surefire-junit4-2.16.jar:2.16]
	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:153) [surefire-junit4-2.16.jar:2.16]
	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:124) [surefire-junit4-2.16.jar:2.16]
	at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:200) [surefire-booter-2.16.jar:2.16]
	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:153) [surefire-booter-2.16.jar:2.16]
	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103) [surefire-booter-2.16.jar:2.16]
Caused by: javassist.compiler.CompileError: empty try block
	at javassist.compiler.MemberCodeGen.atTryStmnt(MemberCodeGen.java:207) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:367) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.CodeGen.atStmnt(CodeGen.java:351) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.ast.Stmnt.accept(Stmnt.java:50) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.CodeGen.atMethodBody(CodeGen.java:292) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.CodeGen.atMethodDecl(CodeGen.java:274) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.ast.MethodDecl.accept(MethodDecl.java:44) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.Javac.compileMethod(Javac.java:169) ~[javassist-3.18.2-GA.jar:na]
	at javassist.compiler.Javac.compile(Javac.java:95) ~[javassist-3.18.2-GA.jar:na]
	at javassist.CtNewMethod.make(CtNewMethod.java:74) ~[javassist-3.18.2-GA.jar:na]
	... 44 common frames omitted
```

**Comment by andy-trimble** [comment]
Implemented a fix in the agent.
