### ISSUE TITLE
java.lang.ClassCastException io.bigio.benchmark.throughput.ThroughputMessage cannot be cast to io.bigio.core.codec.BigIOMessage

### ISSUE THREAD

**Issue by sarfarazengglb** [Archarithms/bigio#33]
Hi Team,

This error is found in every example and test class.Can you advice how to fix the Issue.

20:51:20.156 [Thread-0] ERROR io.bigio.core.codec.GenericCodec - Exception serializing.
java.lang.ClassCastException: io.bigio.benchmark.throughput.ThroughputMessage cannot be cast to io.bigio.core.codec.BigIOMessage
    at io.bigio.core.codec.GenericCodec.encode(GenericCodec.java:94) ~[classes/:na]
    at io.bigio.core.ClusterService.sendMessage(ClusterService.java:263) [classes/:na]
    at io.bigio.core.ClusterService.sendMessage(ClusterService.java:282) [classes/:na]
    at io.bigio.BigIO.send(BigIO.java:169) [classes/:na]
    at io.bigio.BigIO.send(BigIO.java:142) [classes/:na]

**Comment by andy-trimble** [comment]
Hello,

There are two reasons why this exception might be thrown. 

1. The @Message annotation is missing from the message being sent
2. The agent has not been attached to the runtime

In order to attach the agent to the runtime, ensure that the following parameter is being used when starting a BigIO enabled program:

```
-javaagent:<path to bigio-agent jar file>
```

**Comment by andy-trimble** [comment]
I updated the main wiki page to include documentation to this effect. Please verify that this corrects the problem and I will close the issue.

**Comment by sarfarazengglb** [comment]
As adviced i am using same code.Used latest Maven and agent jar.I am working with two different process.In one process i have made producer(with listener and sender) and in other consumer(Only listener).

If i run the producer directly it is working fine it is injecting properly.But if i start Producer Process and consumer Process than it is processing Producer's message listener and when it is delivering the message of separate Consumer listener it is throwing nullpointer.I did step by step debug a debug trace i found this line is giving issue.

 ret = (byte[])((BigIOMessage)message).bigioencode();

Strangle both uses same code.First cycle is working as accepted but second instance listner making issue
   public static byte[] encode(Object message) throws IOException {

```
    if(message.getClass().getAnnotation(io.bigio.Message.class) != null) {
        try {
            byte[] ret;
            ret = (byte[])((BigIOMessage)message).bigioencode();
            return ret;
        } catch (Exception ex) {
            LOG.error("Exception serializing.", ex);
        }
    }

    return null;
}
```

I am using Netbeans to run the process.Both use same code same JDK 1.8.
![bigioissue_nullpointer](https://cloud.githubusercontent.com/assets/6543585/10402563/c1af45a6-6ee3-11e5-9922-b1f4083fa1c5.jpg)

**Comment by andy-trimble** [comment]
How are you executing the processes? Are you using NetBeans, or do you have a script to handle that? Can you provide the commands you're executing for both the consumer and the producer?

**Comment by sarfarazengglb** [comment]
I am using Netbeans to run the process.
My OS is windows 10 and Acer Device
Tried with both github code and Maven dependency from rep.
JDK is 1.8
I also implemented bigiodecode and  bigioencode and changed the line to below it worked  with two process but that is not good approach.Messaging need to use default feature as it is designed and encrypt message automatically.
As i am using IDE it produce the bootup by itself.

 // ret = (byte[])((BigIOMessage)message).bigioencode();
                ret = (byte[]) message.getClass().getMethod("bigioencode").invoke(message);

![maven](https://cloud.githubusercontent.com/assets/6543585/10404460/95b022a6-6ef0-11e5-897d-0faedef9e7b3.jpg)

Producer 
cd C:\Personal\My Project\Sample\BigIOApp; "JAVA_HOME=C:\Program Files\Java\jdk1.8.0_45" cmd /c "\"\"C:\Program Files\NetBeans 8.0.2\java\maven\bin\mvn.bat\" -Dexec.args=\"-classpath %classpath io.bigio.examples.helloworld.Producer\" -Dexec.executable=\"C:\Program Files\Java\jdk1.8.0_45\bin\java.exe\" -Dexec.classpathScope=runtime -Dmaven.ext.class.path=\"C:\Program Files\NetBeans 8.0.2\java\maven-nblib\netbeans-eventspy.jar;C:\Program Files\NetBeans 8.0.2\java\maven-nblib\netbeans-cos.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""

Consumer
cd C:\Personal\My Project\Sample\BigIOApp; "JAVA_HOME=C:\Program Files\Java\jdk1.8.0_45" cmd /c "\"\"C:\Program Files\NetBeans 8.0.2\java\maven\bin\mvn.bat\" -Dexec.args=\"-classpath %classpath io.bigio.examples.helloworld.Consumer\" -Dexec.executable=\"C:\Program Files\Java\jdk1.8.0_45\bin\java.exe\" -Dexec.classpathScope=runtime -Dmaven.ext.class.path=\"C:\Program Files\NetBeans 8.0.2\java\maven-nblib\netbeans-eventspy.jar;C:\Program Files\NetBeans 8.0.2\java\maven-nblib\netbeans-cos.jar\" -Dfile.encoding=UTF-8 org.codehaus.mojo:exec-maven-plugin:1.2.1:exec\""

**Comment by andy-trimble** [comment]
It is not necessary (and will cause errors) to implement bigioencode and bigiodecode. Rather, add an execution flag "-javaagent=C:/some/directory/bigio-agent-1.2.jar". I'm unsure how to do this in NetBeans, but you should be able to configure your project to include this runtime flag.

Take a look [here](http://docs.oracle.com/javase/7/docs/api/java/lang/instrument/package-summary.html) to read about how Java Agents work.

**Comment by sarfarazengglb** [comment]
It is working.Thank you Andy.

java -javaagent:bin/bigio-agent-1.2.jar -Xmx2048m -Xms2048m -cp "bin/<YourBuildName>.jar;config;lib/_;components/_" <YourClassName>

Modified the assemble file.
